const data = {
    products: [
        {
            _id:'1',
            name:'Nike Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'120',
            countInStock:'5',
            brand:'Nike',
            rating:'5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'2',
            name:'Cool case',
            category:'cabinet',
            image:'/image/product1.jpg',
            price:'1200',
            countInStock:'41',
            brand:'cool',
            rating:'4.5',
            numReviews:'16',
            discription:'high quality product',
        },
        {
            _id:'3',
            name:'Rev case',
            category:'cabinet',
            image:'/image/product1.jpg',
            price:'1000',
            countInStock:'23',
            brand:'Nike',
            rating:'5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'4',
            name:'Bear Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'150',
            countInStock:'50',
            brand:'Bear',
            rating:'4.5',
            numReviews:'20',
            discription:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'120',
            countInStock:'210',
            brand:'Nike',
            rating:'3.5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'6',
            name:'Puma Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'100',
            countInStock:'105',
            brand:'Puma',
            rating:'5',
            numReviews:'15',
            discription:'high quality product',
        },
        
    ],
};
export default data;