const data = {
    products: [
        {
            _id:'1',
            name:'Nike Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'120',
            brand:'Nike',
            rating:'5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'2',
            name:'Cool case',
            category:'cabinet',
            image:'/image/product1.jpg',
            price:'1200',
            brand:'cool',
            rating:'4.5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'3',
            name:'Rev case',
            category:'cabinet',
            image:'/image/product1.jpg',
            price:'1000',
            brand:'Nike',
            rating:'5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'4',
            name:'Bear Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'150',
            brand:'Bear',
            rating:'4.5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'120',
            brand:'Nike',
            rating:'5',
            numReviews:'10',
            discription:'high quality product',
        },
        {
            _id:'6',
            name:'Puma Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'100',
            brand:'Puma',
            rating:'5',
            numReviews:'15',
            discription:'high quality product',
        },
        {
            _id:'7',
            name:'Puma Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'100',
            brand:'Puma',
            rating:'5',
            numReviews:'15',
            discription:'high quality product',
        },
        {
            _id:'8',
            name:'Puma Shirt',
            category:'shirts',
            image:'/image/product1.jpg',
            price:'100',
            brand:'Puma',
            rating:'5',
            numReviews:'15',
            discription:'high quality product',
        },
    ],
};
export default data;